# Generated by Django 5.2.8 on 2025-11-27 02:05

import django.db.models.deletion
import my_apps.accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USUARIO', 'Usuario'), ('ENCUESTADOR', 'Encuestador')], default='USUARIO', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.cliente'),
        ),
        migrations.CreateModel(
            name='InvitacionEncuestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_uso', models.PositiveIntegerField(default=1)),
                ('usado', models.PositiveIntegerField(default=0)),
                ('expiracion', models.DateTimeField(default=my_apps.accounts.models.InvitacionEncuestador.fecha_expiracion_default)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='accounts.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
    ]
