# Generated by Django 5.2.8 on 2025-11-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisosencuesta',
            name='puede_editar',
        ),
    ]
