# Generated by Django 5.2.8 on 2025-11-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cliente_alter_profile_options_alter_profile_cargo_and_more'),
        ('encuestas', '0002_remove_permisosencuesta_puede_editar'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='accounts.cliente'),
            preserve_default=False,
        ),
    ]
